"use client";

import { useCallback, useEffect, useRef, useState } from "react";

type SourceKind = "drums" | "bass" | "voice";
type AudioRig = { context: AudioContext; input: GainNode; compressor: DynamicsCompressorNode; makeup: GainNode; dry: GainNode; wet: GainNode; master: GainNode; pre: AnalyserNode; post: AnalyserNode; timer: number; step: number };

const presets = {
  "Gentle glue": { threshold: -16, ratio: 2, attack: 30, release: 220, knee: 18, makeup: 2 },
  "Punch keeper": { threshold: -20, ratio: 4, attack: 45, release: 110, knee: 8, makeup: 3 },
  "Smooth vocal": { threshold: -24, ratio: 3, attack: 12, release: 170, knee: 24, makeup: 4 },
  "Room crusher": { threshold: -32, ratio: 12, attack: 2, release: 65, knee: 2, makeup: 7 },
};

const lessons = [
  { n:"01", title:"Find the threshold", body:"Lower the threshold until only the loudest peaks cross the orange line. That is the moment the compressor begins working." },
  { n:"02", title:"Choose the squeeze", body:"Ratio decides how strongly signals above the threshold are held back. Compare 2:1 with 8:1 at the same threshold." },
  { n:"03", title:"Shape the motion", body:"Attack decides whether the front edge survives. Release decides how quickly the sound breathes back to normal." },
  { n:"04", title:"Compare fairly", body:"Compression often sounds quieter. Add makeup gain, then bypass. Equal loudness reveals the character—not just a volume change." },
];

function dbToGain(db:number){ return Math.pow(10, db / 20); }

export function CompressorLab(){
  const [threshold,setThreshold]=useState(-18), [ratio,setRatio]=useState(4), [attack,setAttack]=useState(25), [release,setRelease]=useState(180), [knee,setKnee]=useState(12), [makeup,setMakeup]=useState(3);
  const [source,setSource]=useState<SourceKind>("drums"), [playing,setPlaying]=useState(false), [bypass,setBypass]=useState(false), [lesson,setLesson]=useState(0), [reduction,setReduction]=useState(0), [challenge,setChallenge]=useState<null|boolean>(null);
  const rig=useRef<AudioRig|null>(null), canvas=useRef<HTMLCanvasElement|null>(null), sourceRef=useRef<SourceKind>(source), raf=useRef(0);
  sourceRef.current=source;

  const scheduleTone=useCallback((r:AudioRig, step:number)=>{
    const c=r.context, now=c.currentTime+.03, type=sourceRef.current;
    const connect=(node:AudioNode)=>node.connect(r.input);
    if(type==="drums"){
      if(step%4===0){ const o=c.createOscillator(), g=c.createGain(); o.frequency.setValueAtTime(125,now);o.frequency.exponentialRampToValueAtTime(45,now+.15);g.gain.setValueAtTime(1,now);g.gain.exponentialRampToValueAtTime(.001,now+.28);o.connect(g);connect(g);o.start(now);o.stop(now+.3); }
      if(step%4===2){ const len=c.sampleRate*.16, b=c.createBuffer(1,len,c.sampleRate), d=b.getChannelData(0);for(let i=0;i<len;i++)d[i]=(Math.random()*2-1)*(1-i/len);const s=c.createBufferSource(),f=c.createBiquadFilter(),g=c.createGain();s.buffer=b;f.type="bandpass";f.frequency.value=1800;g.gain.value=.62;s.connect(f).connect(g);connect(g);s.start(now); }
      const h=c.createOscillator(), hg=c.createGain();h.type="square";h.frequency.value=6200;hg.gain.setValueAtTime(step%2?.025:.055,now);hg.gain.exponentialRampToValueAtTime(.001,now+.035);h.connect(hg);connect(hg);h.start(now);h.stop(now+.04);
    } else if(type==="bass"){
      const notes=[55,55,65.41,73.42,55,82.41,73.42,49]; const o=c.createOscillator(), sub=c.createOscillator(), f=c.createBiquadFilter(), g=c.createGain();o.type="sawtooth";sub.type="sine";o.frequency.value=notes[step%8];sub.frequency.value=notes[step%8]/2;f.type="lowpass";f.frequency.setValueAtTime(step%4===0?900:420,now);g.gain.setValueAtTime(step%4===0?.5:.28,now);g.gain.exponentialRampToValueAtTime(.015,now+.22);o.connect(f);sub.connect(f);f.connect(g);connect(g);o.start(now);sub.start(now);o.stop(now+.24);sub.stop(now+.24);
    } else {
      const melody=[220,246.94,261.63,220,196,220,293.66,261.63], o=c.createOscillator(),f=c.createBiquadFilter(),g=c.createGain();o.type="triangle";o.frequency.value=melody[step%8];f.type="bandpass";f.frequency.value=900;f.Q.value=.7;const accent=step%8===0||step%8===5?.6:.22;g.gain.setValueAtTime(.001,now);g.gain.linearRampToValueAtTime(accent,now+.035);g.gain.exponentialRampToValueAtTime(.001,now+.34);o.connect(f).connect(g);connect(g);o.start(now);o.stop(now+.36);
    }
  },[]);

  const start=useCallback(()=>{
    if(rig.current){ rig.current.context.resume(); setPlaying(true); return; }
    const context=new AudioContext(), input=context.createGain(), compressor=context.createDynamicsCompressor(), makeupNode=context.createGain(), dry=context.createGain(), wet=context.createGain(), master=context.createGain(), pre=context.createAnalyser(), post=context.createAnalyser();
    pre.fftSize=256;post.fftSize=256;master.gain.value=.72;input.connect(pre);input.connect(dry).connect(master);input.connect(compressor).connect(makeupNode).connect(wet).connect(master);master.connect(post).connect(context.destination);dry.gain.value=0;wet.gain.value=1;
    compressor.threshold.value=threshold;compressor.ratio.value=ratio;compressor.attack.value=attack/1000;compressor.release.value=release/1000;compressor.knee.value=knee;makeupNode.gain.value=dbToGain(makeup);
    const r:AudioRig={context,input,compressor,makeup:makeupNode,dry,wet,master,pre,post,timer:0,step:0};rig.current=r;scheduleTone(r,0);r.step=1;r.timer=window.setInterval(()=>scheduleTone(r,r.step++),250);setPlaying(true);
  },[attack,knee,makeup,ratio,release,scheduleTone,threshold]);
  const togglePlay=()=>{ if(!playing) start(); else if(rig.current){rig.current.context.suspend();setPlaying(false);} };
  useEffect(()=>{const r=rig.current;if(!r)return;r.compressor.threshold.setTargetAtTime(threshold,r.context.currentTime,.015);r.compressor.ratio.setTargetAtTime(ratio,r.context.currentTime,.015);r.compressor.attack.setTargetAtTime(attack/1000,r.context.currentTime,.015);r.compressor.release.setTargetAtTime(release/1000,r.context.currentTime,.015);r.compressor.knee.setTargetAtTime(knee,r.context.currentTime,.015);r.makeup.gain.setTargetAtTime(dbToGain(makeup),r.context.currentTime,.015)},[threshold,ratio,attack,release,knee,makeup]);
  useEffect(()=>{const r=rig.current;if(!r)return;r.dry.gain.setTargetAtTime(bypass?1:0,r.context.currentTime,.01);r.wet.gain.setTargetAtTime(bypass?0:1,r.context.currentTime,.01)},[bypass]);
  useEffect(()=>{const draw=()=>{const c=canvas.current,r=rig.current;if(c&&r){const dpr=Math.min(devicePixelRatio,2),w=c.clientWidth,h=c.clientHeight;if(c.width!==w*dpr||c.height!==h*dpr){c.width=w*dpr;c.height=h*dpr}const x=c.getContext("2d")!;x.setTransform(dpr,0,0,dpr,0,0);x.clearRect(0,0,w,h);const a=new Uint8Array(r.pre.frequencyBinCount),b=new Uint8Array(r.post.frequencyBinCount);r.pre.getByteTimeDomainData(a);r.post.getByteTimeDomainData(b);const line=(data:Uint8Array,color:string,y:number,scale:number)=>{x.beginPath();x.strokeStyle=color;x.lineWidth=2;data.forEach((v,i)=>{const px=i/(data.length-1)*w,py=y+(v-128)/128*scale;(i?x.lineTo(px,py):x.moveTo(px,py))});x.stroke()};line(a,"#8aa197",h*.28,h*.18);line(b,"#f26430",h*.72,h*.18);setReduction(Math.round(Math.abs(r.compressor.reduction)*10)/10)}raf.current=requestAnimationFrame(draw)};draw();return()=>cancelAnimationFrame(raf.current)},[]);
  useEffect(()=>()=>{if(rig.current){clearInterval(rig.current.timer);rig.current.context.close()}},[]);
  const applyPreset=(name:keyof typeof presets)=>{const p=presets[name];setThreshold(p.threshold);setRatio(p.ratio);setAttack(p.attack);setRelease(p.release);setKnee(p.knee);setMakeup(p.makeup)};
  const hear=threshold>-10?"Almost nothing is crossing the threshold. Expect a very subtle change.":ratio>9&&attack<8?"Expect a flattened, urgent sound: peaks are caught fast and squeezed hard.":attack>35?"Listen for the initial punch getting through before the body is pulled down.":release<90?"The level snaps back quickly. Listen for audible pumping or extra groove.":"Listen for peaks stepping back while the quieter body feels more present.";
  const curvePoints=Array.from({length:22},(_,i)=>{const input=-48+i*(48/21);const over=input-threshold;const output=over<=0?input:threshold+over/ratio;return {x:(input+48)/48*100,y:100-(output+48)/48*100}});

  return <main>
    <header className="topbar"><a className="brand" href="#top"><span className="brandMark">CL</span><span>Compression Lab</span></a><nav><a href="#concept">How it works</a><a href="#lab">The lab</a><a href="#check">Final check</a></nav><a className="lessonLink" href="#lab">Open the lab <span>↘</span></a></header>
    <section className="hero" id="top"><div className="eyebrow"><span/>An interactive listening lesson</div><h1>Make loud and soft<br/>feel <em>intentional.</em></h1><p className="lede">Why does one word vanish while the next leaps out? Compression reshapes those changes. Hear it, see it, then learn to control it.</p><a className="primaryButton" href="#concept">Start the lesson <span>↓</span></a><div className="heroAside"><span>4 steps</span><p><strong>No theory required</strong>Prediction → listening → explanation → your turn.</p></div></section>
    <section className="concept" id="concept"><div className="sectionNumber">01 / THE IDEA</div><div><p className="kicker">Start with the problem</p><h2>A volume hand<br/>that moves <em>for you.</em></h2></div><div className="conceptCopy"><p>A compressor turns a signal down only when it gets too loud. You choose where it wakes up, how firmly it acts, and how quickly it moves.</p><div className="analogy"><span>BELOW THRESHOLD</span><strong>Hands off</strong><i/><span>ABOVE THRESHOLD</span><strong>Turn it down</strong></div><p className="takeaway"><b>Core idea</b> Compression reduces dynamic range: the distance between quiet and loud moments.</p></div></section>
    <section className="labSection" id="lab"><div className="labTitle"><div><p className="kicker">02 / The listening lab</p><h2>Shape the dynamics.</h2></div><p>Choose a loop, press play, then move one control at a time. Headphones help.</p></div>
      <div className="labShell"><div className="transport"><button className={`playButton ${playing?"playing":""}`} onClick={togglePlay} aria-label={playing?"Pause loop":"Play loop"}>{playing?"‖":"▶"}</button><div className="sourceChooser"><span className="tinyLabel">SOURCE</span>{(["drums","bass","voice"] as SourceKind[]).map(s=><button key={s} className={source===s?"active":""} onClick={()=>setSource(s)}>{s==="voice"?"Vocal-like":s[0].toUpperCase()+s.slice(1)}</button>)}</div><div className="waveLive"><canvas ref={canvas}/><span>IN</span><span>OUT</span></div><button className={`bypass ${bypass?"active":""}`} onClick={()=>setBypass(!bypass)}><i/> {bypass?"Bypassed":"Compressor on"}</button></div>
        <div className="presetBar"><span>STARTING POINTS</span>{Object.keys(presets).map(p=><button key={p} onClick={()=>applyPreset(p as keyof typeof presets)}>{p}</button>)}</div>
        <div className="controlGrid"><div className="mainGraph"><div className="graphHeader"><span>INPUT → OUTPUT</span><strong>{reduction.toFixed(1)} dB gain reduction</strong></div><div className="curveGraph"><div className="zone safe" style={{width:`${(threshold+48)/48*100}%`}}><span>Unaffected zone</span></div><div className="zone working" style={{left:`${(threshold+48)/48*100}%`}}><span>Compression zone</span></div><div className="unityDiag"/>{curvePoints.map((p,i)=>i<curvePoints.length-1&&<i key={i} className="curveSeg" style={{left:`${p.x}%`,top:`${p.y}%`,width:`${Math.hypot(curvePoints[i+1].x-p.x,curvePoints[i+1].y-p.y)}%`,transform:`rotate(${Math.atan2(curvePoints[i+1].y-p.y,curvePoints[i+1].x-p.x)*180/Math.PI}deg)`}}/>)}<div className="thresholdLine" style={{left:`${(threshold+48)/48*100}%`}}><span>{threshold} dB</span></div><b className="axisY">OUTPUT LEVEL</b><b className="axisX">INPUT LEVEL</b></div><div className="graphLegend"><span><i className="beforeDot"/>No compression</span><span><i className="afterDot"/>Your setting</span></div><div className="reductionMeter"><span>GAIN REDUCTION</span><div><i style={{width:`${Math.min(reduction/18*100,100)}%`}}/></div><strong>{reduction.toFixed(1)} dB</strong></div></div>
          <div className="controls"><Control name="Threshold" hint="When it starts" value={threshold} display={`${threshold} dB`} min={-48} max={0} step={1} set={setThreshold}/><Control name="Ratio" hint="How firmly" value={ratio} display={`${ratio}:1`} min={1} max={20} step={1} set={setRatio}/><div className="timingPair"><Control name="Attack" hint="How fast it grabs" value={attack} display={`${attack} ms`} min={1} max={100} step={1} set={setAttack}/><Control name="Release" hint="How fast it lets go" value={release} display={`${release} ms`} min={40} max={800} step={10} set={setRelease}/></div><div className="timingPair"><Control name="Knee" hint="Soft or sudden" value={knee} display={`${knee} dB`} min={0} max={40} step={1} set={setKnee}/><Control name="Makeup" hint="Restore loudness" value={makeup} display={`+${makeup} dB`} min={0} max={12} step={.5} set={setMakeup}/></div><p className="listenCard"><span>WHAT TO HEAR NOW</span>{hear}</p></div></div>
      </div>
    </section>
    <section className="guided"><div className="guidedIntro"><p className="kicker">03 / Guided experiments</p><h2>One move<br/>at a time.</h2><p>Compression gets mysterious when every knob changes at once. These four passes isolate the job of each control.</p></div><div className="lessonPanel"><div className="lessonTabs">{lessons.map((l,i)=><button className={lesson===i?"active":""} onClick={()=>setLesson(i)} key={l.n}><span>{l.n}</span>{l.title}</button>)}</div><article><span className="bigNumber">{lessons[lesson].n}</span><p className="kicker">Listening experiment</p><h3>{lessons[lesson].title}</h3><p>{lessons[lesson].body}</p><div className="tryBox"><b>Try this</b>{lesson===0&&"Play drums. Slide threshold from −6 dB to −30 dB. Notice when the meter wakes up."}{lesson===1&&"Set threshold to −24 dB. Alternate ratio between 2:1 and 10:1."}{lesson===2&&"Load Punch keeper. Move attack from 2 ms to 60 ms and focus on the kick’s first instant."}{lesson===3&&"Toggle Compressor on / Bypassed. Adjust makeup until neither side simply sounds louder."}</div><div className="lessonNav"><button disabled={lesson===0} onClick={()=>setLesson(v=>v-1)}>← Back</button><button disabled={lesson===3} onClick={()=>setLesson(v=>v+1)}>Next experiment →</button></div></article></div></section>
    <section className="finalCheck" id="check"><p className="kicker">04 / Final knowledge check</p><h2>A snare has lost its punch.<br/>What would you change first?</h2><div className="answers"><button onClick={()=>setChallenge(false)} className={challenge===false?"wrong":""}>Make the attack faster</button><button onClick={()=>setChallenge(true)} className={challenge===true?"right":""}>Make the attack slower</button><button onClick={()=>setChallenge(false)} className={challenge===false?"wrong":""}>Raise the ratio to 20:1</button></div>{challenge!==null&&<p className={`feedback ${challenge?"right":"wrong"}`}>{challenge?"Exactly. A slower attack lets the snare’s initial transient pass before compression pulls down the body.":"Not quite. Those choices catch or flatten more of the transient. Let the compressor react later instead."}</p>}</section>
    <section className="conclusion"><span>YOU NOW HAVE THE MAP</span><h2>Threshold says <em>when.</em><br/>Ratio says <em>how much.</em><br/>Timing says <em>how it feels.</em></h2><p>Return to the opening problem: an uneven vocal becomes steadier because peaks cross the threshold and are turned down. Makeup gain then brings the controlled performance forward.</p><a href="#lab">Keep experimenting ↑</a></section>
    <footer><a className="brand" href="#top"><span className="brandMark">CL</span><span>Compression Lab</span></a><p>Original browser-synthesized loops. No audio files or backend required.</p></footer>
  </main>
}

function Control({name,hint,value,display,min,max,step,set}:{name:string;hint:string;value:number;display:string;min:number;max:number;step:number;set:(v:number)=>void}){return <label className="control"><span><b>{name}</b><small>{hint}</small></span><output>{display}</output><input aria-label={name} type="range" value={value} min={min} max={max} step={step} onChange={e=>set(Number(e.target.value))}/><i className="rangeEnds"><em>{min}</em><em>{max}</em></i></label>}
