"use client";

import { useEffect, useRef, useState } from "react";

type ExcerptKind = "opening" | "whisper" | "surge";
type AudioRig = { context: AudioContext; element: HTMLAudioElement; input: GainNode; compressor: DynamicsCompressorNode; makeup: GainNode; dry: GainNode; wet: GainNode; master: GainNode; pre: AnalyserNode; post: AnalyserNode };

const excerpts: Record<ExcerptKind, { label:string; start:number; end:number; note:string }> = {
  opening: { label:"Opening impact", start:0, end:28, note:"The famous opening moves between forceful chords and shorter, quieter answers." },
  whisper: { label:"Quiet tension", start:82, end:112, note:"A restrained passage makes it easier to hear exactly when the threshold begins working." },
  surge: { label:"Full orchestra", start:270, end:302, note:"Dense orchestral peaks reveal heavy compression, pumping, and lost transient detail." },
};

const presets = {
  "Gentle glue": { threshold: -16, ratio: 2, attack: 30, release: 220, knee: 18, makeup: 2 },
  "Punch keeper": { threshold: -20, ratio: 4, attack: 45, release: 110, knee: 8, makeup: 3 },
  "Smooth vocal": { threshold: -24, ratio: 3, attack: 12, release: 170, knee: 24, makeup: 4 },
  "Room crusher": { threshold: -32, ratio: 12, attack: 2, release: 65, knee: 2, makeup: 7 },
};

const lessons = [
  { n:"01", title:"Find the threshold", body:"Lower the threshold until only the loudest peaks cross the orange line. That is the moment the compressor begins working." },
  { n:"02", title:"Choose the squeeze", body:"Ratio decides how strongly signals above the threshold are held back. Compare 2:1 with 8:1 at the same threshold." },
  { n:"03", title:"Shape the motion", body:"Attack decides whether the front edge survives. Release decides how quickly the sound breathes back to normal." },
  { n:"04", title:"Compare fairly", body:"Compression often sounds quieter. Add makeup gain, then bypass. Equal loudness reveals the character—not just a volume change." },
];

function dbToGain(db:number){ return Math.pow(10, db / 20); }

export function CompressorLab(){
  const [threshold,setThreshold]=useState(-18), [ratio,setRatio]=useState(4), [attack,setAttack]=useState(25), [release,setRelease]=useState(180), [knee,setKnee]=useState(12), [makeup,setMakeup]=useState(3);
  const [excerpt,setExcerpt]=useState<ExcerptKind>("opening"), [playing,setPlaying]=useState(false), [bypass,setBypass]=useState(false), [lesson,setLesson]=useState(0), [reduction,setReduction]=useState(0), [challenge,setChallenge]=useState<null|boolean>(null);
  const rig=useRef<AudioRig|null>(null), canvas=useRef<HTMLCanvasElement|null>(null), raf=useRef(0);

  const start=async()=>{
    if(rig.current){ await rig.current.context.resume(); await rig.current.element.play(); setPlaying(true); return; }
    const context=new AudioContext(), input=context.createGain(), compressor=context.createDynamicsCompressor(), makeupNode=context.createGain(), dry=context.createGain(), wet=context.createGain(), master=context.createGain(), pre=context.createAnalyser(), post=context.createAnalyser();
    const element=new Audio(new URL("audio/beethoven-5.mp3", window.location.href).href);element.loop=false;element.preload="auto";element.currentTime=excerpts[excerpt].start;context.createMediaElementSource(element).connect(input);
    pre.fftSize=256;post.fftSize=256;master.gain.value=.9;input.connect(pre);input.connect(dry).connect(master);input.connect(compressor).connect(makeupNode).connect(wet).connect(master);master.connect(post).connect(context.destination);dry.gain.value=0;wet.gain.value=1;
    compressor.threshold.value=threshold;compressor.ratio.value=ratio;compressor.attack.value=attack/1000;compressor.release.value=release/1000;compressor.knee.value=knee;makeupNode.gain.value=dbToGain(makeup);
    const r:AudioRig={context,element,input,compressor,makeup:makeupNode,dry,wet,master,pre,post};rig.current=r;await element.play();setPlaying(true);
  };
  const togglePlay=()=>{ if(!playing) void start(); else if(rig.current){rig.current.element.pause();setPlaying(false);} };
  const chooseExcerpt=(next:ExcerptKind)=>{setExcerpt(next);const r=rig.current;if(r){r.element.currentTime=excerpts[next].start;if(playing)void r.element.play()}};
  useEffect(()=>{const r=rig.current;if(!r)return;r.compressor.threshold.setTargetAtTime(threshold,r.context.currentTime,.015);r.compressor.ratio.setTargetAtTime(ratio,r.context.currentTime,.015);r.compressor.attack.setTargetAtTime(attack/1000,r.context.currentTime,.015);r.compressor.release.setTargetAtTime(release/1000,r.context.currentTime,.015);r.compressor.knee.setTargetAtTime(knee,r.context.currentTime,.015);r.makeup.gain.setTargetAtTime(dbToGain(makeup),r.context.currentTime,.015)},[threshold,ratio,attack,release,knee,makeup]);
  useEffect(()=>{const r=rig.current;if(!r)return;r.dry.gain.setTargetAtTime(bypass?1:0,r.context.currentTime,.01);r.wet.gain.setTargetAtTime(bypass?0:1,r.context.currentTime,.01)},[bypass]);
  useEffect(()=>{const draw=()=>{const c=canvas.current,r=rig.current;if(c&&r){const dpr=Math.min(devicePixelRatio,2),w=c.clientWidth,h=c.clientHeight;if(c.width!==w*dpr||c.height!==h*dpr){c.width=w*dpr;c.height=h*dpr}const x=c.getContext("2d")!;x.setTransform(dpr,0,0,dpr,0,0);x.clearRect(0,0,w,h);const a=new Uint8Array(r.pre.frequencyBinCount),b=new Uint8Array(r.post.frequencyBinCount);r.pre.getByteTimeDomainData(a);r.post.getByteTimeDomainData(b);const line=(data:Uint8Array,color:string,y:number,scale:number)=>{x.beginPath();x.strokeStyle=color;x.lineWidth=2;data.forEach((v,i)=>{const px=i/(data.length-1)*w,py=y+(v-128)/128*scale;(i?x.lineTo(px,py):x.moveTo(px,py))});x.stroke()};line(a,"#8aa197",h*.28,h*.18);line(b,"#f26430",h*.72,h*.18);setReduction(Math.round(Math.abs(r.compressor.reduction)*10)/10)}raf.current=requestAnimationFrame(draw)};draw();return()=>cancelAnimationFrame(raf.current)},[]);
  useEffect(()=>{const r=rig.current;if(r)r.element.currentTime=excerpts[excerpt].start},[excerpt]);
  useEffect(()=>()=>{if(rig.current){rig.current.element.pause();rig.current.context.close()}},[]);
  const applyPreset=(name:keyof typeof presets)=>{const p=presets[name];setThreshold(p.threshold);setRatio(p.ratio);setAttack(p.attack);setRelease(p.release);setKnee(p.knee);setMakeup(p.makeup)};
  const hear=threshold>-10?"Almost nothing is crossing the threshold. Expect a very subtle change.":ratio>9&&attack<8?"Expect a flattened, urgent sound: peaks are caught fast and squeezed hard.":attack>35?"Listen for the initial punch getting through before the body is pulled down.":release<90?"The level snaps back quickly. Listen for audible pumping or extra groove.":"Listen for peaks stepping back while the quieter body feels more present.";
  const compressedOutput=(input:number)=>{
    if(knee<=0)return input<=threshold?input:threshold+(input-threshold)/ratio;
    const kneeStart=threshold-knee/2, kneeEnd=threshold+knee/2;
    if(input<kneeStart)return input;
    if(input>kneeEnd)return threshold+(input-threshold)/ratio;
    return input+(1/ratio-1)*Math.pow(input-kneeStart,2)/(2*knee);
  };
  const curvePoints=Array.from({length:81},(_,i)=>{const input=-48+i*(48/80),output=Math.max(-48,Math.min(0,compressedOutput(input)));return {x:(input+48)/48*100,y:100-(output+48)/48*100}});
  const curvePath=curvePoints.map(p=>`${p.x.toFixed(2)},${p.y.toFixed(2)}`).join(" ");
  const thresholdPosition=(threshold+48)/48*100;

  return <main>
    <header className="topbar"><a className="brand" href="#top"><span className="brandMark">CL</span><span>Compression Lab</span></a><nav><a href="#concept">How it works</a><a href="#lab">The lab</a><a href="#check">Final check</a></nav><a className="lessonLink" href="#lab">Open the lab <span>↘</span></a></header>
    <section className="hero" id="top"><div className="eyebrow"><span/>An interactive listening lesson</div><h1>Make loud and soft<br/>feel <em>intentional.</em></h1><p className="lede">How can an orchestra lean toward a whisper, then hit like a wall? Use Beethoven’s Fifth to hear, see, and control those dramatic changes.</p><a className="primaryButton" href="#concept">Start the lesson <span>↓</span></a><div className="heroAside"><span>4 steps</span><p><strong>One real performance</strong>Prediction → listening → explanation → your turn.</p></div></section>
    <section className="concept" id="concept"><div className="sectionNumber">01 / THE IDEA</div><div><p className="kicker">Start with the problem</p><h2>A volume hand<br/>that moves <em>for you.</em></h2></div><div className="conceptCopy"><p>A compressor turns a signal down only when it gets too loud. You choose where it wakes up, how firmly it acts, and how quickly it moves.</p><div className="analogy"><span>BELOW THRESHOLD</span><strong>Hands off</strong><i/><span>ABOVE THRESHOLD</span><strong>Turn it down</strong></div><p className="takeaway"><b>Core idea</b> Compression reduces dynamic range: the distance between quiet and loud moments.</p></div></section>
    <section className="labSection" id="lab"><div className="labTitle"><div><p className="kicker">02 / The listening lab</p><h2>Shape the dynamics.</h2></div><p>Choose a passage from Beethoven’s Fifth, press play, then move one control at a time. Headphones help.</p></div>
      <div className="labShell"><div className="transport"><button className={`playButton ${playing?"playing":""}`} onClick={togglePlay} aria-label={playing?"Pause Beethoven":"Play Beethoven"}>{playing?"‖":"▶"}</button><div className="sourceChooser"><span className="tinyLabel">BEETHOVEN 5 · MOVEMENT I</span>{(Object.keys(excerpts) as ExcerptKind[]).map(key=><button key={key} className={excerpt===key?"active":""} onClick={()=>chooseExcerpt(key)}>{excerpts[key].label}</button>)}</div><div className="waveLive"><canvas ref={canvas}/><span>IN</span><span>OUT</span></div><button className={`bypass ${bypass?"active":""}`} onClick={()=>setBypass(!bypass)}><i/> {bypass?"Bypassed":"Compressor on"}</button></div>
        <p className="excerptNote"><b>Listen at this moment:</b> {excerpts[excerpt].note}</p>
        <div className="presetBar"><span>STARTING POINTS</span>{Object.keys(presets).map(p=><button key={p} onClick={()=>applyPreset(p as keyof typeof presets)}>{p}</button>)}</div>
        <div className="controlGrid"><div className="mainGraph"><div className="graphHeader"><span>HOW INPUT LOUDNESS BECOMES OUTPUT LOUDNESS</span><strong>{reduction.toFixed(1)} dB gain reduction</strong></div><div className="curveGraph"><div className="zone safe" style={{width:`${thresholdPosition}%`}}><span>Below threshold</span></div><div className="zone working" style={{left:`${thresholdPosition}%`}}><span>Above threshold</span></div><svg className="transferCurve" viewBox="0 0 100 100" preserveAspectRatio="none" role="img" aria-labelledby="curveTitle curveDescription"><title id="curveTitle">Compressor input-to-output curve</title><desc id="curveDescription">The orange line shows output with the current compressor settings. The gray dashed line shows where levels above the threshold would go without compression.</desc><polyline className="settingCurve" points={curvePath}/><line className="referenceCurve" x1={thresholdPosition} y1={100-thresholdPosition} x2="100" y2="0"/></svg><div className="thresholdLine" style={{left:`${thresholdPosition}%`}}><span>{threshold} dB threshold</span></div><b className="axisY">OUTPUT LEVEL</b><b className="axisX">INPUT LEVEL</b></div><div className="curveExplainer"><p><i className="grayLine"/><span><strong>Gray dashed = no compression</strong>It is a reference showing where loud signals would go if the compressor did nothing. Below the threshold it sits directly under the orange line.</span></p><p><i className="orangeLine"/><span><strong>Orange solid = your output</strong>When it bends flatter, loud input produces less output—the compressor is turning peaks down.</span></p></div>{knee>0&&<p className="kneeNote">The rounded bend near the threshold comes from your <strong>{knee} dB soft knee</strong>.</p>}<div className="reductionMeter"><span>GAIN REDUCTION</span><div><i style={{width:`${Math.min(reduction/18*100,100)}%`}}/></div><strong>{reduction.toFixed(1)} dB</strong></div></div>
          <div className="controls"><Control name="Threshold" hint="When it starts" value={threshold} display={`${threshold} dB`} min={-48} max={0} step={1} set={setThreshold}/><Control name="Ratio" hint="How firmly" value={ratio} display={`${ratio}:1`} min={1} max={20} step={1} set={setRatio}/><div className="timingPair"><Control name="Attack" hint="How fast it grabs" value={attack} display={`${attack} ms`} min={1} max={100} step={1} set={setAttack}/><Control name="Release" hint="How fast it lets go" value={release} display={`${release} ms`} min={40} max={800} step={10} set={setRelease}/></div><div className="timingPair"><Control name="Knee" hint="Soft or sudden" value={knee} display={`${knee} dB`} min={0} max={40} step={1} set={setKnee}/><Control name="Makeup" hint="Restore loudness" value={makeup} display={`+${makeup} dB`} min={0} max={12} step={.5} set={setMakeup}/></div><p className="listenCard"><span>WHAT TO HEAR NOW</span>{hear}</p></div></div>
      </div>
    </section>
    <section className="guided"><div className="guidedIntro"><p className="kicker">03 / Guided experiments</p><h2>One move<br/>at a time.</h2><p>Compression gets mysterious when every knob changes at once. These four passes isolate the job of each control.</p></div><div className="lessonPanel"><div className="lessonTabs">{lessons.map((l,i)=><button className={lesson===i?"active":""} onClick={()=>setLesson(i)} key={l.n}><span>{l.n}</span>{l.title}</button>)}</div><article><span className="bigNumber">{lessons[lesson].n}</span><p className="kicker">Listening experiment</p><h3>{lessons[lesson].title}</h3><p>{lessons[lesson].body}</p><div className="tryBox"><b>Try this</b>{lesson===0&&"Choose Quiet tension. Slide threshold from −6 dB to −30 dB and watch when the meter wakes up."}{lesson===1&&"Choose Full orchestra, set threshold to −24 dB, then alternate ratio between 2:1 and 10:1."}{lesson===2&&"Choose Opening impact. Move attack from 2 ms to 60 ms and focus on the first edge of each chord."}{lesson===3&&"Toggle Compressor on / Bypassed. Adjust makeup until neither side simply sounds louder."}</div><div className="lessonNav"><button disabled={lesson===0} onClick={()=>setLesson(v=>v-1)}>← Back</button><button disabled={lesson===3} onClick={()=>setLesson(v=>v+1)}>Next experiment →</button></div></article></div></section>
    <section className="finalCheck" id="check"><p className="kicker">04 / Final knowledge check</p><h2>A snare has lost its punch.<br/>What would you change first?</h2><div className="answers"><button onClick={()=>setChallenge(false)} className={challenge===false?"wrong":""}>Make the attack faster</button><button onClick={()=>setChallenge(true)} className={challenge===true?"right":""}>Make the attack slower</button><button onClick={()=>setChallenge(false)} className={challenge===false?"wrong":""}>Raise the ratio to 20:1</button></div>{challenge!==null&&<p className={`feedback ${challenge?"right":"wrong"}`}>{challenge?"Exactly. A slower attack lets the snare’s initial transient pass before compression pulls down the body.":"Not quite. Those choices catch or flatten more of the transient. Let the compressor react later instead."}</p>}</section>
    <section className="conclusion"><span>YOU NOW HAVE THE MAP</span><h2>Threshold says <em>when.</em><br/>Ratio says <em>how much.</em><br/>Timing says <em>how it feels.</em></h2><p>Return to the opening problem: Beethoven’s quiet passages remain open while orchestral peaks cross the threshold and are turned down. Makeup gain then brings the controlled performance forward.</p><a href="#lab">Keep experimenting ↑</a></section>
    <footer><a className="brand" href="#top"><span className="brandMark">CL</span><span>Compression Lab</span></a><p>Beethoven, Symphony No. 5, movement I · Skidmore College Orchestra · <a href="https://commons.wikimedia.org/wiki/File:Ludwig_van_Beethoven_-_symphony_no._5_in_c_minor,_op._67_-_i._allegro_con_brio.ogg" target="_blank" rel="noreferrer">Public domain recording</a></p></footer>
  </main>
}

function Control({name,hint,value,display,min,max,step,set}:{name:string;hint:string;value:number;display:string;min:number;max:number;step:number;set:(v:number)=>void}){return <label className="control"><span><b>{name}</b><small>{hint}</small></span><output>{display}</output><input aria-label={name} type="range" value={value} min={min} max={max} step={step} onChange={e=>set(Number(e.target.value))}/><i className="rangeEnds"><em>{min}</em><em>{max}</em></i></label>}
